name: Build and Deploy to myserver

on:
  push:
    branches:
      - main  # デプロイ対象のブランチを指定

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          #extended: true

      - name: Build
        run: hugo --minify --baseURL "https://cookiehookey.redirectme.net/blog/"

      - name: SFTP upload to myserver
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASS }}
          localDir: './public'
          remoteDir: '/www'
          options: '--delete'
